development:
  adapter: mysql
  database: sixsigma_development
  username: ss
  password: phi
  host: localhost

test:
  adapter: mysql
  database: sixsigma_test
  username: ss_test
  password: phi_test
  host: localhost

production:
  adapter: mysql
  database: sixsigma_production
  username: root
  password: 
  host: localhost
